/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import domains.*;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static windows.MenuWindow.sound;

/**
 *
 * @author felip
 */
public class WindowMatch extends javax.swing.JFrame implements Observer{

   private Game game;
   private WindowGameBoard windowGameBoard;

    public WindowMatch(Game aGame) {
        initComponents();
        game = aGame;
        windowGameBoard = new WindowGameBoard(aGame);
        game.addObserver(this);
        try {
            FondoSwing fondo = new FondoSwing(ImageIO.read(new File("src/resources/1.jpg")));
            JPanel panel = (JPanel) this.getContentPane();
            panel.setBorder(fondo);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTransparent();
    }

    public void setTransparent() {
        ArrayList jbuttons = new ArrayList<>();
        jbuttons.add(btnSound);
        for (int i = 0; i < jbuttons.size(); i++) {
            JButton buttonAux = (JButton) jbuttons.get(i);
            buttonAux.setOpaque(false);
            buttonAux.setContentAreaFilled(false);
            buttonAux.setBorderPainted(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWayToFinish = new javax.swing.JLabel();
        lblRedPlayer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListWayToFinish = new javax.swing.JList<>();
        txtRedPlayer = new javax.swing.JTextField();
        lblBluePlayer = new javax.swing.JLabel();
        txtBluePlyaer = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSound = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWayToFinish.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblWayToFinish.setForeground(new java.awt.Color(255, 255, 255));
        lblWayToFinish.setText("Forma de finalizar el juego:");
        getContentPane().add(lblWayToFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, -1, -1));

        lblRedPlayer.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblRedPlayer.setForeground(new java.awt.Color(255, 255, 255));
        lblRedPlayer.setText("Jugador Rojo:");
        getContentPane().add(lblRedPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        jListWayToFinish.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListWayToFinish);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 450, 230, 90));

        txtRedPlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtRedPlayer.setOpaque(false);
        txtRedPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRedPlayerActionPerformed(evt);
            }
        });
        getContentPane().add(txtRedPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 160, 30));

        lblBluePlayer.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblBluePlayer.setForeground(new java.awt.Color(255, 255, 255));
        lblBluePlayer.setText("Jugador Azul:");
        getContentPane().add(lblBluePlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, -1, -1));

        txtBluePlyaer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtBluePlyaer.setOpaque(false);
        getContentPane().add(txtBluePlyaer, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, 160, 30));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Datos de la partida");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, -1, -1));

        jButton1.setText("Comenzar Partida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 670, 150, 50));

        btnSound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/speakerOn-img.png"))); // NOI18N
        btnSound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoundActionPerformed(evt);
            }
        });
        getContentPane().add(btnSound, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 700, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRedPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRedPlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRedPlayerActionPerformed

    private void btnSoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoundActionPerformed
        if(game.isStateMusic()){
           game.setStateMusic(false);
       }else{
           game.setStateMusic(true);
       }
    }//GEN-LAST:event_btnSoundActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        windowGameBoard.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSound;
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jListWayToFinish;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBluePlayer;
    private javax.swing.JLabel lblRedPlayer;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWayToFinish;
    private javax.swing.JTextField txtBluePlyaer;
    private javax.swing.JTextField txtRedPlayer;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        ImageIcon iconOff = new ImageIcon(getClass().getResource("/resources/speakerOff-img.png"));
        ImageIcon iconOn = new ImageIcon(getClass().getResource("/resources/speakerOn-img.png"));
        if(game.isStateMusic()){
            btnSound.setIcon(iconOn);
            sound.play();
        }else{
            btnSound.setIcon(iconOff);
            sound.stop();
        }
    }
}
