/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import domains.*;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import static windows.MenuWindow.sound;

/**
 *
 * @author felip
 */
public class WindowMatch extends javax.swing.JFrame implements Observer{

   private Game game;
   private WindowGameBoard windowGameBoard;
    private MenuWindow menuWindow;
    
    public WindowMatch(Game aGame, MenuWindow mainWindow) {
        initComponents();
        game = aGame;
        menuWindow = mainWindow;
        windowGameBoard = new WindowGameBoard(aGame, menuWindow);
        game.addObserver(this);
        try {
            FondoSwing fondo = new FondoSwing(ImageIO.read(new File("src/resources/1.jpg")));
            JPanel panel = (JPanel) this.getContentPane();
            panel.setBorder(fondo);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTransparent();
    }

    public void setTransparent() {
        ArrayList jbuttons = new ArrayList<>();
        ArrayList jRadioButtons = new ArrayList<>();
        jbuttons.add(btnSound);
        
        jRadioButtons.add(jrdMovements);
        jRadioButtons.add(jrdOneToken);
        jRadioButtons.add(jrdAllTokens);
        for (int i = 0; i < jbuttons.size(); i++) {
            JButton buttonAux = (JButton) jbuttons.get(i);
            buttonAux.setOpaque(false);
            buttonAux.setContentAreaFilled(false);
            buttonAux.setBorderPainted(false);
        }
        
        for (int i = 0; i < jRadioButtons.size(); i++) {
            JRadioButton radioButtonAux = (JRadioButton) jRadioButtons.get(i);
            radioButtonAux.setOpaque(false);
            radioButtonAux.setContentAreaFilled(false);
            radioButtonAux.setBorderPainted(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblWayToFinish = new javax.swing.JLabel();
        lblRedPlayer = new javax.swing.JLabel();
        lblBluePlayer = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSound = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jrdMovements = new javax.swing.JRadioButton();
        jrdOneToken = new javax.swing.JRadioButton();
        jrdAllTokens = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                manageClosingWindow(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWayToFinish.setFont(new java.awt.Font("Snubnose DEMO", 0, 36)); // NOI18N
        lblWayToFinish.setForeground(new java.awt.Color(255, 255, 255));
        lblWayToFinish.setText("Forma de finalizar el juego:");
        getContentPane().add(lblWayToFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, -1, -1));

        lblRedPlayer.setFont(new java.awt.Font("Snubnose DEMO", 0, 36)); // NOI18N
        lblRedPlayer.setForeground(new java.awt.Color(255, 255, 255));
        lblRedPlayer.setText("Jugador Rojo:");
        getContentPane().add(lblRedPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        lblBluePlayer.setFont(new java.awt.Font("Snubnose DEMO", 0, 36)); // NOI18N
        lblBluePlayer.setForeground(new java.awt.Color(255, 255, 255));
        lblBluePlayer.setText("Jugador Azul:");
        getContentPane().add(lblBluePlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        lblTitle.setFont(new java.awt.Font("Snubnose DEMO", 0, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Datos de la partida");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, -1, -1));

        jButton1.setText("Comenzar Partida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 630, 150, 50));

        btnSound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/speakerOn-img.png"))); // NOI18N
        btnSound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoundActionPerformed(evt);
            }
        });
        getContentPane().add(btnSound, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 700, -1, -1));

        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 390, 110));

        jScrollPane3.setViewportView(jList2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 390, 110));

        buttonGroup1.add(jrdMovements);
        jrdMovements.setFont(new java.awt.Font("Snubnose DEMO", 0, 20)); // NOI18N
        jrdMovements.setForeground(new java.awt.Color(255, 255, 255));
        jrdMovements.setText("Movimientos");
        getContentPane().add(jrdMovements, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 530, -1, -1));

        buttonGroup1.add(jrdOneToken);
        jrdOneToken.setFont(new java.awt.Font("Snubnose DEMO", 0, 20)); // NOI18N
        jrdOneToken.setForeground(new java.awt.Color(255, 255, 255));
        jrdOneToken.setText("Llevar una pieza");
        getContentPane().add(jrdOneToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 530, -1, -1));

        buttonGroup1.add(jrdAllTokens);
        jrdAllTokens.setFont(new java.awt.Font("Snubnose DEMO", 0, 20)); // NOI18N
        jrdAllTokens.setForeground(new java.awt.Color(255, 255, 255));
        jrdAllTokens.setText("LLevar todas las piezas");
        getContentPane().add(jrdAllTokens, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 530, -1, -1));

        jTextField1.setEnabled(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 580, 50, 30));

        jLabel1.setFont(new java.awt.Font("Snubnose DEMO", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cantidad de Movimientos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 580, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoundActionPerformed
        if(game.isStateMusic()){
           game.setStateMusic(false);
       }else{
           game.setStateMusic(true);
       }
    }//GEN-LAST:event_btnSoundActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        windowGameBoard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void manageClosingWindow(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_manageClosingWindow
        menuWindow.setVisible(true);
        
    }//GEN-LAST:event_manageClosingWindow
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSound;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton jrdAllTokens;
    private javax.swing.JRadioButton jrdMovements;
    private javax.swing.JRadioButton jrdOneToken;
    private javax.swing.JLabel lblBluePlayer;
    private javax.swing.JLabel lblRedPlayer;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWayToFinish;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        ImageIcon iconOff = new ImageIcon(getClass().getResource("/resources/speakerOff-img.png"));
        ImageIcon iconOn = new ImageIcon(getClass().getResource("/resources/speakerOn-img.png"));
        if(game.isStateMusic()){
            btnSound.setIcon(iconOn);
            sound.play();
        }else{
            btnSound.setIcon(iconOff);
            sound.stop();
        }
    }
}
